### ISSUE TITLE
need your help 

### ISSUE THREAD

**Issue by ghost** [Lucklyric/InSAR-Simulator#1]
Why is there no result when running simulator.py with the environment configured? 
Can you provide a perfectly working version? thank you!

**Comment by Lucklyric** [comment]
Dear @akls332 could you provide more information and context. There are some others who sent me an email regarding the usage and configuration. However, I have not heard of any problems with producing outputs. Which branch are you using? For https://github.com/Lucklyric/InSAR-Simulator/blob/DeepInSAR-v1/simulator.py you should able to get simulation data under `$WORKDIR/sim_data` by `python simulator.py`. The default configuration takes a quite long time to finish data generation based on your CPU resources. Are there any errors thrown out by the application if you are still unable to obtain output?

**Comment by ocalvoa** [comment]
Hi Lucklyric, 
I was trying to run your repository, but I have some errors in the environment. Could you provide the version of each library? Nowadays, some methods are deprecated and do not run anymore. 
Thank you in advance!
